### ISSUE TITLE
Miner won't run in Awesome Miner (Windows OP SYS)

### ISSUE THREAD

**Issue by CryptominerPaul** [technobyl/CryptoDredge#2]
Initialize diagnostics (40)
Starting Diagnostics. Awesome Miner version: 5.1.3
Starting Mining Software
Setting up Miner Engine. Instance: 4
Engine Type: 21, Auto Download: False, EnginePath: C:\Minerprograms\Cryptodredge\CryptoDredge.exe, Subtype: Disabled, CustomExecutable: 
Added rule for: C:\Minerprograms\Cryptodredge\CryptoDredge.exe
C:\Minerprograms\Cryptodredge\CryptoDredge.exe  -d 0 -i 18 -a lyra2z -o stratum+tcp://mct.pickaxe.pro:4558 -u MBv1uorHy6DF7KhFEmQZvt8ZHRirdJQ2RV.MSIGPU0 -p c=MCT -b 0.0.0.0:4031   (WindowMode: ConsoleFormat, EngineType: 21, IsProfitMiner: True)
Configuration: 

Configured command line: 
-d 0 -i 18
> Error parsing options: Option 'b' does not exist
Failed to start miner process: Process has exited, so the requested information is not available.
Failed to start miner in Diagnostics mode
Diagnostics completed

**Comment by CreamyG31337** [comment]
there's no API so the -b option is not recognized. set up with compatibility mode none and manually enter the rest of the options. go read the readme, -i 18 isn't going to work either.

**Comment by CryptominerPaul** [comment]
I did read the "read me" also I changed the -i 18 - unless your going to add the -b option by adding API in a future update I'm sure a lot of rookie AM users will not use your miner.

**Comment by CryptoDredge** [comment]
The ccminer 2.3 compatible API was added since version 0.6.0
