### ISSUE TITLE
Where is Cuda 9.1 versions?

### ISSUE THREAD

**Issue by V3T3RaN** [technobyl/CryptoDredge#29]
I have P102-100 and his latest driver [389.07] support only Cuda 9.1. 
New drivers [416.34-64] after change .inf files don't installing successfully. So, Cuda v9.1 version is needed!11

**Comment by V3T3RaN** [comment]
Why u stop building Cuda 9.1 versions?

**Comment by V3T3RaN** [comment]
lul, v11 has Cuda 9.1 on linux, but n0t Win version =C

**Comment by dropdeadrus** [comment]
> I have P102-100 and his latest driver [389.07] support only Cuda 9.1.
> New drivers [416.34-64] after change .inf files don't installing successfully. So, Cuda v9.1 version is needed!11

you can add P102-100 strings to the INF file of the latest driver and it will work with P102-100s and CUDA 10 just fine. 🤷‍♂️

google "nvidia inf patch".

**Comment by V3T3RaN** [comment]
Thanks for the answer, but you apparently did not read my message well, I wrote that I changed nv_dispi.inf, and the installation started, but ended with an error.

![default](https://user-images.githubusercontent.com/29987714/49037222-b52b4600-f1ca-11e8-9a87-95496acc9030.png)

**Comment by V3T3RaN** [comment]
I just tried disable the driver signature check and it worked, thanks!11 ;-D

**Comment by CryptoDredge** [comment]
Solved

**Comment by FrostieKek** [comment]
> have you disabled the driver signature checks?
> 
> I have one rig with P102-100s running on 416.34 with modded inf file. works fine, no issues
I've tried this a few months back and get windows error code 43 on 441.12(even with a signed cat)
