### ISSUE TITLE
My anti-virus software found a possible virus in the release versions of this software

### ISSUE THREAD

**Issue by pavulon18** [technobyl/CryptoDredge#32]
Type:
Threat detected in compressed files

Description:
C:\Users\pavul\Downloads\CryptoDredge_0.10.0_cuda_9.2_windows.zip=>CryptoDredge_0.10.0\CryptoDredge.exe : Win32/Virus.RiskTool.e58

Scan Engine:
360 Cloud Scan Engine

Location:
C:\Users\pavul\Downloads\CryptoDredge_0.10.0_cuda_9.2_windows.zip

Suggestion:
Quarantined files

**Comment by CryptoDredge** [comment]
CryptoDredge is not a piece of malicious software. You may try to add an exception in antivirus software you use.
