### ISSUE TITLE
mtp low difficulty problem 0.15.2 build for linux

### ISSUE THREAD

**Issue by toptim** [technobyl/CryptoDredge#41]
please check
`INFO  - 48/0 Accepted : diff=1.53419e-05 : 27.47MH/s
INFO  - Rejected share: Low difficulty
INFO  - 48/1 Rejected : diff=1.72639e-05
INFO  - 49/1 Accepted : diff=2.07823e-05 : 27.47MH/s
kernel: [ 4879.735048] show_signal_msg: 18 callbacks suppressed
kernel: [ 4879.735053] CryptoDredge[3501]: segfault at 561b8166bd60 ip 0000561b7c944cc7 sp 00007f4325ffa7a0 error 6 in CryptoDredge[561b7c76f000+16f4000]
3464 Segmentation fault      (core dumped) ~/cryptodredge/CryptoDredge_0.15.2/CryptoDredge -c ~/cryptodredge/mintpondxzc.json`

**Comment by toptim** [comment]
manual set difficulty help me
1100 for 1070 and 1400 for 1070ti

**Comment by baf28** [comment]
Khs * 0.33 = set diff
2*1080=5500*0.33=1815
