### ISSUE TITLE
[Question] What is reasoning for removal of algorithms

### ISSUE THREAD

**Issue by LeadManPL** [technobyl/CryptoDredge#45]
As in subject, What is reasoning for removal of algorithms in 0.16.1
If this is for speed optimisation, maybe you could provide additional algorithms as some modules?

**Comment by FelixVVV** [comment]
The official response in the Discord  channel is - **because Skein is under ASIC** , but Skein has been under ASIC since February 2018, however, this did not prevent mining some coins on the GPU all last year.
