### ISSUE TITLE
Hashrate drops after devfee session

### ISSUE THREAD

**Issue by GrannyCryptomaster** [technobyl/CryptoDredge#46]
Mining CN Haven with 7 GTX 1060 3GB in Windows 10 x64. 
After first devfee session, hashrate drops with over 6%. Than slowly recovers, but not at the initial speed. Than after each devfee session drops and recovers, but not at the top speed that showed at start. Is this drop real? Or the way that hashrate is calculated is to blame?

**Comment by cdarken** [comment]
Same for mining lyra3v3, a drop from 26.9 to 26.35.

**Comment by platinum4** [comment]
Duplicate non-issue since it is not displaying the lost hash rate when dev mining

https://github.com/technobyl/CryptoDredge/issues/33

@GrannyCryptomaster Please close duplicate issue
