### ISSUE TITLE
Api is not always started in 0.8.2

### ISSUE THREAD

**Issue by Quake4** [technobyl/CryptoDredge#9]
https://bitcointalk.org/index.php?topic=4807821.msg43566283#msg43566283

**Comment by webgkv** [comment]
It's works in different way with different algo, same like this:

       {"Allium": "-a allium -b 127.0.0.1:4068"},
                {"blake2s":"-a blake2s"},
                {"lyra2v2" : "-a lyra2v2 --api-type ccminer-tcp -b 127.0.0.1:4068 "},
                {"lyra2z" : "-a lyra2z -b 127.0.0.1:4068" },
                {"Neoscrypt":"-a neoscrypt --api-type ccminer-tcp -b 127.0.0.1:4068 " },
                {"phi":"-a phi"},
                {"skein" : "-a skein"},
                {"skunk":"-a skunk"},
                {"Tribus":"-a tribus --api-type ccminer-tcp -b 127.0.0.1:4068"}

After restart it's can needs to change  for only "-b 127.0.0.1:4068" or  also also
 
  0.8 work in API mode by default on all algo grate, Please! back it!
